import type { ForgeReport } from "./logic";

export function reportToJSON(report: ForgeReport): string {
  return JSON.stringify(report, null, 2);
}

export function reportToTXT(report: ForgeReport): string {
  const lines: string[] = [];
  lines.push("CYBERFORGE SECURITY REPORT");
  lines.push("=".repeat(40));
  lines.push(`Target: ${report.target}`);
  lines.push(`Analysis date: ${new Date(report.generatedAt).toISOString()}`);
  lines.push("");

  lines.push("DNS FINDINGS");
  lines.push("-".repeat(40));
  for (const section of report.dns) {
    lines.push(`${section.type}:`);
    if (section.error) {
      lines.push(`  error: ${section.error}`);
    } else if (section.answers.length === 0) {
      lines.push("  (no records)");
    } else {
      for (const a of section.answers) lines.push(`  ${a.data}  (TTL ${a.ttl}s)`);
    }
  }
  lines.push("");

  lines.push("HTTP FINDINGS");
  lines.push("-".repeat(40));
  if (report.http) {
    lines.push(`Status: ${report.http.status} ${report.http.statusText}`);
    if (report.http.finalUrl !== report.http.requestedUrl) {
      lines.push(`Redirected to: ${report.http.finalUrl}`);
    }
  } else {
    lines.push(`Could not complete: ${report.httpError}`);
  }
  lines.push("");

  lines.push("SECURITY HEADERS");
  lines.push("-".repeat(40));
  for (const h of report.securityHeaders) {
    lines.push(`${h.present ? "[present]" : "[missing]"} ${h.header}${h.value ? `: ${h.value}` : ""}`);
  }
  lines.push("");

  lines.push("SECURITY.TXT");
  lines.push("-".repeat(40));
  lines.push(report.http?.securityTxt ? report.http.securityTxt.trim() : "Not found.");
  lines.push("");

  lines.push("OBSERVATIONS & RECOMMENDATIONS");
  lines.push("-".repeat(40));
  for (const obs of report.observations) lines.push(`· ${obs}`);
  lines.push("");

  lines.push("Generated by CyberForge — analyze.understand.defend");

  return lines.join("\n");
}

export async function reportToPDF(report: ForgeReport): Promise<Blob> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  function ensureSpace(next: number) {
    if (y + next > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  }

  function heading(text: string) {
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 20, 22);
    doc.text(text, margin, y);
    y += 8;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 18;
  }

  function body(text: string, mono = false) {
    doc.setFont(mono ? "courier" : "helvetica", "normal");
    doc.setFontSize(mono ? 9 : 10.5);
    doc.setTextColor(60, 60, 64);
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      ensureSpace(14);
      doc.text(line, margin, y);
      y += 14;
    }
    y += 4;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 15, 17);
  doc.text("CyberForge Security Report", margin, y);
  y += 26;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(110, 110, 115);
  doc.text(`Target: ${report.target}`, margin, y);
  y += 14;
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, margin, y);
  y += 26;

  heading("DNS Findings");
  for (const section of report.dns) {
    const line = section.error
      ? `${section.type}: error — ${section.error}`
      : section.answers.length === 0
        ? `${section.type}: no records`
        : `${section.type}: ${section.answers.map((a) => a.data).join(", ")}`;
    body(line, true);
  }

  heading("HTTP Findings");
  if (report.http) {
    body(`Status: ${report.http.status} ${report.http.statusText}`, true);
    if (report.http.finalUrl !== report.http.requestedUrl) {
      body(`Redirected to: ${report.http.finalUrl}`, true);
    }
  } else {
    body(`Could not complete: ${report.httpError}`);
  }

  heading("Security Headers");
  for (const h of report.securityHeaders) {
    body(`${h.present ? "[present]" : "[missing]"} ${h.header}${h.value ? `: ${h.value}` : ""}`, true);
  }

  heading("security.txt");
  body(report.http?.securityTxt ? report.http.securityTxt.trim() : "Not found.", true);

  heading("Observations & Recommendations");
  for (const obs of report.observations) body(`· ${obs}`);

  return doc.output("blob");
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadText(text: string, filename: string, mime: string) {
  downloadBlob(new Blob([text], { type: mime }), filename);
}
